// Power Bank: (Parts based off watching Dissi)
// ATK 50 (25/25) Move/Atk
// HEAL 32 (16/16) Move/Heal
// HEAL 32 (16/16) Move/Heal
[MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK,ATTACK]
[MOVE,MOVE,MOVE,MOVE,HEAL,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,HEAL,HEAL,HEAL,MOVE,MOVE,MOVE,HEAL,HEAL,HEAL]
